# Generated by Django 5.0.6 on 2024-05-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('stock_quantity', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PackagingTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('material', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnitsOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('required_tools', models.CharField(max_length=100)),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.packagingtypes')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='packaging_types',
            field=models.ManyToManyField(to='inventory.packagingtypes'),
        ),
        migrations.AddField(
            model_name='items',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitsofmeasurement'),
        ),
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assigned_to', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.billofmaterials')),
            ],
        ),
    ]
