# Generated by Django 5.0.6 on 2024-05-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_packagingtypes_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingtypes',
            name='level',
            field=models.CharField(max_length=20),
        ),
    ]
