# Generated by Django 5.0.6 on 2024-05-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_packagingtypes_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingtypes',
            name='level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary')], max_length=20),
        ),
    ]
