# Generated by Django 5.0.6 on 2024-05-28 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_packagingmaterials_alter_packagingtypes_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingmaterials',
            name='available_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='packagingmaterials',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='packagingmaterials',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='packagingmaterials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='packagingtypes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='packagingtypes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
