# Generated by Django 5.0.6 on 2024-05-29 10:19

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_packagingmaterials_available_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('warehouse_type', models.IntegerField(choices=[(1, 'Type1'), (2, 'Type2')])),
                ('description', tinymce.models.HTMLField(blank=True, max_length=50)),
                ('total_capacity', models.IntegerField()),
                ('available_capacity', models.IntegerField()),
                ('unit_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.unittype')),
            ],
        ),
    ]
