# Generated by Django 5.0.6 on 2024-05-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_unittype_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='unit_type',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='UnitType',
        ),
    ]
