# Generated by Django 5.0.6 on 2024-05-30 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_warehouse_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingtypes',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
