# Generated by Django 5.0.6 on 2024-05-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_packagingtypes_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagingtypes',
            name='warehouse',
        ),
    ]
