# Generated by Django 5.0.6 on 2024-05-30 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_packagingtypes_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='packaging_materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.packagingmaterials'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='packaging_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.packagingtypes'),
        ),
    ]
