# Generated by Django 5.0.6 on 2024-05-30 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_warehouse_packaging_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
