# Generated by Django 5.0.6 on 2024-05-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_items_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='packaging_types',
        ),
        migrations.AddField(
            model_name='items',
            name='packaging_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.packagingtypes'),
        ),
    ]
