# Generated by Django 5.0.6 on 2024-05-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_items_packaging_types_items_packaging_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingmaterials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
