# Generated by Django 5.0.6 on 2024-05-31 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_packagingmaterials_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingmaterials',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
