# Generated by Django 5.0.6 on 2024-06-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_packagingmaterials_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'permissions': [('can_create_bom', 'Can create BOM'), ('can_view_bom', 'Can view BOM'), ('can_update_bom', 'Can update BOM'), ('can_delete_bom', 'Can delete BOM')]},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'permissions': [('can_create_item', 'Can create item'), ('can_view_item', 'Can view item'), ('can_update_item', 'Can update item'), ('can_delete_item', 'Can delete item')]},
        ),
        migrations.AlterModelOptions(
            name='packaginginstructions',
            options={'permissions': [('can_create_packaging_instruction', 'Can create packaging instruction'), ('can_view_packaging_instruction', 'Can view packaging instruction'), ('can_update_packaging_instruction', 'Can update packaging instruction'), ('can_delete_packaging_instruction', 'Can delete packaging instruction')]},
        ),
        migrations.AlterModelOptions(
            name='packagingmaterials',
            options={'permissions': [('can_create_packaging_material', 'Can create packaging material'), ('can_view_packaging_material', 'Can view packaging material'), ('can_update_packaging_material', 'Can update packaging material'), ('can_delete_packaging_material', 'Can delete packaging material')]},
        ),
        migrations.AlterModelOptions(
            name='packagingtypes',
            options={'permissions': [('can_create_packaging_type', 'Can create packaging type'), ('can_view_packaging_type', 'Can view packaging type'), ('can_update_packaging_type', 'Can update packaging type'), ('can_delete_packaging_type', 'Can delete packaging type')]},
        ),
        migrations.AlterModelOptions(
            name='unitsofmeasurement',
            options={'permissions': [('can_create_unit_of_measurement', 'Can create unit of measurement'), ('can_view_unit_of_measurement', 'Can view unit of measurement'), ('can_update_unit_of_measurement', 'Can update unit of measurement'), ('can_delete_unit_of_measurement', 'Can delete unit of measurement')]},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'permissions': [('can_create_warehouse', 'Can create warehouse'), ('can_view_warehouse', 'Can view warehouse'), ('can_update_warehouse', 'Can update warehouse'), ('can_delete_warehouse', 'Can delete warehouse')]},
        ),
        migrations.AlterModelOptions(
            name='workorders',
            options={'permissions': [('can_create_work_order', 'Can create work order'), ('can_view_work_order', 'Can view work order'), ('can_update_work_order', 'Can update work order'), ('can_delete_work_order', 'Can delete work order')]},
        ),
    ]
