# Generated by Django 5.0.6 on 2024-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_salesorder_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(default='Unknown Contact', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='packaging_materials',
            field=models.ManyToManyField(blank=True, to='inventory.packagingmaterials'),
        ),
    ]
