# Generated by Django 5.0.6 on 2024-06-05 11:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_customer_remove_supplier_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer')),
                ('packaging_types', models.ManyToManyField(blank=True, to='inventory.packagingtypes')),
            ],
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
