# Generated by Django 5.0.6 on 2024-06-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_salesorder1_delete_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder1',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
