# Generated by Django 5.0.6 on 2024-06-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_salesorder1_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder1',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
