# Generated by Django 5.0.6 on 2024-06-07 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_salesorder1_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingtypes',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.packagingtypes'),
        ),
    ]
