# Generated by Django 5.0.6 on 2024-06-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_salesrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
    ]
