# Generated by Django 5.0.6 on 2024-06-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_salesrecord_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
