# Generated by Django 5.0.6 on 2024-06-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_salesrecord_delivery_date_salesrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.items'),
        ),
    ]
